using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace DAL.Model
{
    public class Users
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        [BsonRepresentation(BsonType.ObjectId)]
        public string _id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int Role { get; set; }
    }
}
